name: smart_tourist_guide
version: 0.1.0
publish_to: 'none'

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.2.0
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  google_maps_flutter: ^2.3.0
  http: ^1.1.0
  flutter_tts: ^3.8.2
  audioplayers: ^5.2.1
  path_provider: ^2.1.2
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
